import {
  ScrollText,
  BookText,
  BookMarked,
  ShieldCheck,
  CalendarDays,
  NotebookPen,
  ListChecks,
  FileSignature,
  IdCard,
  FileCheck,
  ShieldAlert,
  FileText,
  FileWarning,
  ClipboardList,
  Tag,
  Star,
  Flag,
  Bug,
  Sparkles,
  Wrench,
  Bookmark,
  Folder,
  Briefcase,
  AlertTriangle,
  CheckSquare,
  Clock,
  Users,
  Mail,
  Shield,
  Lock,
  Key,
  Database,
  Zap,
  Heart,
  Bell,
  Pin,
  type LucideIcon,
} from "lucide-react";

/** Доступные иконки меток (имя → компонент). Имя хранится в labels.icon. */
export const LABEL_ICONS: Record<string, LucideIcon> = {
  ScrollText,
  BookText,
  BookMarked,
  ShieldCheck,
  CalendarDays,
  NotebookPen,
  ListChecks,
  FileSignature,
  IdCard,
  FileCheck,
  ShieldAlert,
  FileText,
  FileWarning,
  ClipboardList,
  Tag,
  Star,
  Flag,
  Bug,
  Sparkles,
  Wrench,
  Bookmark,
  Folder,
  Briefcase,
  AlertTriangle,
  CheckSquare,
  Clock,
  Users,
  Mail,
  Shield,
  Lock,
  Key,
  Database,
  Zap,
  Heart,
  Bell,
  Pin,
};

export const LABEL_ICON_NAMES = Object.keys(LABEL_ICONS);

export function getLabelIcon(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return LABEL_ICONS[name] ?? null;
}
